### ISSUE TITLE
002. Connect to repository

### ISSUE THREAD

**Issue by djplaner** [djplaner/moodle-booktool_github#14]
When
- github if *_off_ and the user wants to turn it on
- they click on the GitHub link in the Book administration menu

What
- Opens up the main config page for book tool asking for username/password and repository
- Password would not be stored, submission of the form with password would invoke the oauth/basic authentication stuff to get the token ?? should it display the token??
- Would need to handle the presence of two-factor authentication - initially perhaps just generate a warning and say can't do it.

For a little later
- If the book tool (in this session) already has an oauth token hopefully this information can be pre-populated (not password - just username)and the user can change these if they wish
- If repository information is loaded, but not username/password, then this can be asked for
- If all information loaded then it can display information about the repository and offer various options to do stuff --- these are to be handled elsewhere.

How
- All being done in index.php and should probably be done with a renderer

**Comment by schme16** [comment]
What kind of renderer did you have in mind?
- Markdown
- HAML
- Straight up HTML
- All of the above?

The GitHuber in me wants to say Markdown (due to its brevity and low learning curve), but I'm not sure how many educators would be interested in learning what may be a new language to them.

**Comment by djplaner** [comment]
The "renderer" above is meant to be a Moodle thing.  Method for displaying content so that it plays nicely with the Moodle template system.  ATM, this will be for the interface used to interact with the Book github tool.

For now, since the aim is to integrate with the Book module, the actual display of the content of the Book will have to be limited to what the Book module uses.  i.e. HTML split into chapters and sub-chapters and stored in the Moodle database.

The question you're asking is about the content of the file stored on github.  This is an open question, though I do have an initial plan.

Like you I don't think most academics are going to bother learning Markdown - yet another language.  I have enough trouble justifying it, and it's a much lower barrier for me.

Initially, my plan is for it to be just a single HTML file.  The content from the Moodle database for the book will be concatenated into a single HTML file. Using something like div tags and two classes to identify Moodle book chapters and sub-chapters.  Perhaps with a default CSS file that will allow that HTML file to be displayed nicely as a stand alone HTML page.  

This is easy to implement. HTML is probably more broadly usable (though not without it's problems). With CSS (which could be modified) it would also be easily read outside of the Moodle book.  A good feature for a project trying to enable OERs.

Longer term, there are at least two other Moodle book tools that import content (HTML and ePub) into the Moodle book.  One option might be to detect those tools and use their functionality. Allow the user to choose which format to use.

**Comment by djplaner** [comment]
Need to implement the form to allow entry of the data and associated logic to handle if it's there or not.
- First ever click on "GitHub" will show instructions of what is required
- Click continue results in showing a form asking for repo and filename
- Form submitted
  *\* if the repo doesn't exist ?? ask to create it - needs extra steps ??
  *\* if the file doesn't exist ?? assume it's empty - and create it??
  *\* Display status of form submission
- Subsequent clicks on "GitHub" show the details of the repo/file and additional information about the status (should be a form with an update button so that change can be done any time)
- The normal display will show options to PULL/PUSH as appropriate.

**Comment by djplaner** [comment]
Done and working
